#!/bin/bash
set -euo pipefail
# This isn't always set (e.g. in Puppet runs).
HOME=${HOME:-~}

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

echo_cmd() {
    echo >&2 "=> $@"
    "$@"
}

echo_cmd git submodule sync
echo_cmd git submodule update --init

for f in *; do
    if [ "$f" = "update" -o "$f" = "scripts" ]; then
        continue
    fi

    dest="$HOME/.$f"
    if [ -d "$dest"  ]; then
        if [ -L "$dest" ]; then
            echo_cmd rm "$dest"
        else
            echo >&2 "already directory: $dest"
            exit 1
        fi
    elif [ -L "$dest" ]; then
        target=$(readlink -f "$dest")
        if [[ "$target" = *-local ]]; then
            echo >&2 "will not override locally-overridden $f (points to $dest)"
            continue
        fi

    fi

    echo_cmd ln -fs "$(readlink -f "$f")" "$dest"
done

echo_cmd mkdir -p ~/.config/xfce4/terminal
echo_cmd ln -fs "$(readlink -f terminalrc)" ~/.config/xfce4/terminal/terminalrc

echo_cmd mkdir -p ~/.config/nvim
echo_cmd rm -f ~/.config/nvim/init.vim
echo_cmd ln -fs "$(readlink -f nvim-init.lua)" ~/.config/nvim/init.lua

for histfile in \
    lesshst \
    grails_history \
    histfile \
    mysql_history \
    nano_history \
    sqlite_history \
    bash_history \
    zsh_history \
    python_history \
; do
    echo_cmd ln -fs /dev/null "$HOME/.$histfile"
done

echo_cmd touch ~/.mutt/muttrc-local
echo_cmd touch ~/.tmux-local.conf
